BlueBrain/hpcbench

setup.py
tox.ini

Just a first commit to see everything is working...

Py33 support remove

---

hpcbench/__init__.py
hpcbench/campaign.py
setup.py
tests/test_campaign.py

Get rid of `packaging` package dependency

Use setuptools_scm to manage package version

---

hpcbench/benchmark/shoc.py
tests/benchmark/test_shoc.gpu.stdout
tests/benchmark/test_shoc.py

- choc benchmark for gpu
compilation:
CUDA_CPPFLAGS="-gencode=arch=compute_35,code=sm_35" ./configure 
35 should change for the futur cluster

 add shoc benchmark

---

hpcbench/benchmark/shoc.py
tests/benchmark/test_shoc.py

- update shoc execution with larger test case (update size of the pb)
- catch the dgemm score

 update shoc for dgemm score

---

docs/index.rst

I just changed the part of the developer documentation to make it a bit clearer

updated documentation for clarity

---

hpcbench/driver.py
hpcbench/toolbox/contextlib_ext.py
tests/test_driver.py
tests/test_pruned_dir.py
tests/test_pruned_dir.yaml

These two commits cover both the report directory pruning and a small fix to take localhost into account.

fix #85 and #100

---

hpcbench/cli/bencsv.py

sorry, only small fix that needed to be added :)

If --fields is not used, pass to export a None

---

hpcbench/driver.py
tests/test_slurm.py

We now catch errors and exceptions, log them and return in case of error -1. We don't throw exceptions here but simply log the error such that other tags can be submitted while the error at the failing job can be investigated by the user. Many errors when calling sbatch can result from bad choice of constraints.

Proper error handling for sbatch call

---

hpcbench/benchmark/osu.py
tests/benchmark/test_osu.osu_alltoallv.stdout
tests/benchmark/test_osu.osu_mbw_mr.stdout
tests/benchmark/test_osu.py

We have now working p2p and collective OSU benchmarks

Updated OSU benchmark to support several new modes from upstream

---

hpcbench/benchmark/minigemm.py

- more precise flop calculation
- use size_t for sizes to also run with bigger matrices
- now use ifndef to be able to easily redefine buffer sizes

slightly improved minigemm benchmark

---

hpcbench/driver.py

ben-sh in sbatch should inherit verbosity from calling ben-sh

Fix sbatch ben-sh verbosity

---

hpcbench/campaign.py
hpcbench/cli/bencsv.py
hpcbench/cli/benelastic.py
hpcbench/driver.py
hpcbench/export/csvexport.py
hpcbench/export/es.py
tests/test_csv.py

* Use campaign YAML config to figure if this is a sbatch report.
* Use class `ReportNode` to extract metrics from report.

Fix function `hpcbench.campaign.get_metrics`

---

hpcbench/driver.py

Use JSON parser instead of YAML's for metrics

---

hpcbench/api.py
hpcbench/benchmark/hpl.py
hpcbench/benchmark/shoc.py
tests/benchmark/test_hpl.py

* adjust results of HPL
* Fix shoc: values were already in gflops
Fixes #180

Get rid of flops metrics, only use gflops

---

hpcbench/benchmark/ior.py

Fix missing context argument to pre_execute method

---

hpcbench/toolbox/process.py
tests/test_slurm.py
tests/test_slurm_sbatch_list_arg.yaml

Allow process/sbatch section values to be lists

---

hpcbench/cli/benwait.py

It takes some time for a job to be accessible via sacct.
Also remove repeating log message.

Fix ben-wait for sbatch launched few ms before

---

hpcbench/driver/slurm.py
hpcbench/toolbox/process.py
tests/test_slurm.py

Set pretty job name in generated sbatches

---

hpcbench/driver/base.py
hpcbench/driver/benchmark.py
hpcbench/driver/campaign.py
hpcbench/driver/executor.py
tests/test_campaign.py
tests/test_driver.py
tests/test_srun.py
tests/test_srun.yaml

Use cartesian product of srun arguments to produce several commands at once
Fixes #231

Use cartesian product of srun arguments to produce several commands at once

---

hpcbench/benchmark/ior.py

The following change aimed to shrink YAML of IOR campaigns
run at BBP.
* api_file_mode_options: a dictionary to specify
additional options according to API and file mode.
Default value:
- if fpp => '-f'
- if MPIIO and onefile => -c
User can override this feature in YAML
* properly handle path with prefix (like `ime://`)
in `pre_execute` hook.
* `clean_path`: new boolean option to remove test directory
if it already exists. Default is True.
* `repetitions`: number of repetitions of test
Fixes #251

ior: new attributes and improvements

---

hpcbench/export/es.py

Do not try to get metrics from failed runs.

Fix ben-elastic crash

---

hpcbench/api.py
hpcbench/benchmark/babelstream.py
hpcbench/benchmark/basic.py
hpcbench/benchmark/custream.py
hpcbench/benchmark/hpl.py
hpcbench/benchmark/imb.py
hpcbench/benchmark/ionvme.py
hpcbench/benchmark/ior.py
hpcbench/benchmark/iperf.py
hpcbench/benchmark/mdtest.py
hpcbench/benchmark/minigemm.py
hpcbench/benchmark/nvidia.py
hpcbench/benchmark/osu.py
hpcbench/benchmark/shoc.py
hpcbench/benchmark/standard.py
hpcbench/benchmark/stream.py
hpcbench/benchmark/sysbench.py
hpcbench/campaign.py
hpcbench/templates/plugins/benchmark/{{cookiecutter.benchmark}}/hpcbench_{{cookiecutter.benchmark}}/benchmark.py
hpcbench/templates/report.tex.jinja
tests/__init__.py
tests/benchmark/benchmark.py
tests/test_environment.py

Now extracts description from class docstring first line.

API: remove Benchmark.description class variable

---

hpcbench/benchmark/imb.py
hpcbench/benchmark/ior.py
hpcbench/benchmark/osu.py
tests/__init__.py
tests/benchmark/benchmark.py

API: benchmark attributes now must have a property with docstring

---

hpcbench/benchmark/hpl.py
hpcbench/benchmark/imb.py
hpcbench/templates/HPL.dat.jinja
setup.py
tests/benchmark/test_hpl.py
tests/benchmark/test_minigemm.py

HPL benchmark now accepts the same parameters than the web form
available at:
http://www.advancedclustering.com/act_kb/tune-hpl-dat-file/
No need to copy paste the form result anymore!

HPL: integate advanceclustering.com web form

---

hpcbench/benchmark/osu.py
tests/benchmark/test_osu.py

#284 fully implemented with unit tests. Please merge if you think it's ok.

Benchmark options
