- hpcbench/campaign.py
- setup.py
Do not assume version of `setuptools` installed and explicitly install `packaging`.
Fix #1
> Add explicit dependency on packaging

- hpcbench/cli/__init__.py
- setup.py
- tox.ini
So that it is not required to install it on nodes where ben-sh is executed.
> Do not make matplotlib mandatory

- hpcbench/campaign.py
Jenkins use a merge commit that cannot be installed with pip
to test pull-requests, for instance:
pip install \
'git+http://github.com/tristan0x/hpcbench@820bf2b#egg=hpcbench'
produces the following error:
fatal: reference is not a tree: 820bf2b27d86d4fdd657a8e461f4183dc
This patch force to retrieve the master version in this case.
> Do not use exact version when building a branch with Travis CI

- hpcbench/benchmark/iossd.py
Darwin does not support linux command line for the IO "vm.drop_caches=3" use correct one.
>  fix bug io for Darwin

- hpcbench/campaign.py
- tests/test_campaign.py
- tests/test_driver.py
In the network section of a campaign we can now create tags that refer to other tags. The tags keyword has to be followed by a list of tag names.
Extended test cases to check recursive tag expansion and cycle detection.
This closes #85
> Network tags can now contain a `tags` keyword to refer to other tags

- docs/campaign.rst
- hpcbench/campaign.py
- hpcbench/driver.py
- hpcbench/templates/executor.sh.jinja
Shell-scripts are based on a Jinja template, which can be
overriden in YAML.
> Always generate shell-scripts to execute benchmarks

- hpcbench/benchmark/osu.py
- setup.py
- tests/benchmark/benchmark.py
- tests/benchmark/test_osu.osu_allgather.stdout
- tests/benchmark/test_osu.osu_allgatherv.stdout
- tests/benchmark/test_osu.osu_bw.stdout
- tests/benchmark/test_osu.osu_latency.stdout
- tests/benchmark/test_osu.py
- tests/test_driver.py
This benchmark module allows running and post-processing:
* osu_latency
* osu_bw
* osu_allgather
* osu_allgatherv
which are the most common benchmarks used for evaluation of interconnect performance.
> OSU benchmarks

- hpcbench/benchmark/osu.py
- hpcbench/driver.py
- hpcbench/toolbox/buildinfo.py
- hpcbench/toolbox/collections_ext.py
- requirements-dev.txt
- setup.py
- tests/__init__.py
- tests/benchmark/benchmark.py
- tests/benchmark/test_osu.osu_allgather.stdout
- tests/benchmark/test_osu.osu_allgatherv.stdout
- tests/benchmark/test_osu.osu_bw.stdout
- tests/benchmark/test_osu.osu_latency.stdout
- tests/benchmark/test_osu.py
- tests/test_driver.py
- tests/test_slurm.py
- tests/test_slurm_default_sbatch_template_per_uc.yaml
- tests/test_slurm_embedded_sbatch_template.yaml
- tests/test_slurm_sbatch_template_per_uc.yaml
- tests/toolbox/test_buildinfo.py
This new feature allows HPCBench to extract a special build_info ELF section that can be included by build systems containing build flags, the configuration and specific dependencies. The information is first extracted using binutils' `objcopy`, parsed as `json` and stored as a dict into the benchmark `metas` dict.
> Extract build information from binaries and store into benchmark metas

- tests/__init__.py
- tests/toolbox/test_buildinfo.py
This PR intends to get rid of the files created in git working copy when executing unit-tests with tox.
> Fix buildinfo UT: create intermediate files and executable in tmp

- hpcbench/toolbox/buildinfo.py
- tests/toolbox/test_buildinfo.py
Added code and test case to correctly catch when objcopy cannot find a buildinfo section but does not return a non-zero exit code.
> Fix issue where objcopy errors were not caught

- hpcbench/driver.py
- tests/test_slurm.py
Passing `--nodelist` option to srun is not enough, `--nodes` seems
also required.
> Fix slurm node restriction when calling srun

- hpcbench/benchmark/imb.py
- hpcbench/benchmark/osu.py
- hpcbench/driver.py
- tests/__init__.py
When declaring metric schemas for lists of dicts of metrics we have to make sure not to declare them as list(dict(name: metric) as this decays to [name]. We should instead the syntax [dict(name: metric)].
Also fixed the metrics schema checker to raise an exception when an invalid metric is found.
> fixed wrong metrics declarations in extractors

- docs/campaign.rst
- hpcbench/api.py
- hpcbench/campaign.py
- hpcbench/cli/benwait.py
- hpcbench/driver.py
- hpcbench/templates/executor.sh.jinja
- hpcbench/toolbox/loader.py
- tests/test_environment.py
- tests/test_environment.yaml
I modified @ohm314 first implementation so that settings in YAML completely overrides what was specified in `Benchmark.execution_context`, so that the user can completely takes over if needed.
What do you think @ohm314 ?
> `environment` and `modules` can be specified in execution_context and YAML

- hpcbench/benchmark/babelstream.py
- hpcbench/benchmark/custream.py
- hpcbench/benchmark/hpl.py
- hpcbench/benchmark/imb.py
- hpcbench/benchmark/ior.py
- hpcbench/benchmark/iperf.py
- hpcbench/benchmark/nvidia.py
- hpcbench/benchmark/osu.py
- hpcbench/benchmark/shoc.py
- hpcbench/benchmark/stream.py
- hpcbench/toolbox/process.py
- tests/toolbox/test_process.py
- changed find_executable semantics to return name if not found and `required=False`.
- changed in most benchmarks the call to find_executable to non-required, i.e. if executable is not found we carry on with the provided name. This behavior is usually more appropriate as executable name could be only resolvbed in the execution script after loading module
> not finding exe should not cause failure in most benchmarks

- hpcbench/__init__.py
The strings are escaped to HTML which causes e.g. slurm jobs to crash since constraints may contain escaped characters.
> disable autoescaping for strings in jinja templates

- hpcbench/__init__.py
- hpcbench/campaign.py
- hpcbench/driver.py
- hpcbench/templates/executor.sh.jinja
- hpcbench/toolbox/environment_modules.py
- tests/test_environment.py
- tests/test_environment.yaml
Set environment in `pre_execute` and `post_execute` member methods
according to `environment` and `modules` execution settings.
> Set process environment in Benchmark hook member methods

- hpcbench/api.py
- hpcbench/benchmark/basic.py
- hpcbench/benchmark/hpl.py
- hpcbench/benchmark/mdtest.py
- hpcbench/benchmark/minigemm.py
- hpcbench/driver.py
- tests/__init__.py
- tests/benchmark/test_mdtest.py
- tests/test_campaign.py
- tests/test_environment.py
Benchmark pre_execute and post_execute hooks can now access the same execution context that the main execution has. This allows them to use for instance the logger.
This closes #184
> Added execution context into pre_execute and post_execute hooks

- hpcbench/campaign.py
- hpcbench/cli/benumb.py
- hpcbench/export/csvexport.py
- hpcbench/export/es.py
Neither environment variables nor network section should be expanded when we
are traversing the campaign for exporting, reporting, etc. These actions are
typically done at a later point in time and not necessarily on the same
system and would fail when we try to expand the original environment.
NB: we should consider storing the campaign file in expanded form in the
report directory, cf. #220
> Don't expand the campaign when not in data generation mode

- hpcbench/benchmark/ior.py
this enables us to express import IOR parameters directly in yaml (rather than raw shell command arguments). They can be passed as scalars or lists allowing us to run scaling tests:
```
ior_bench:
type: ior
attributes: 
executable: /usr/local/bin/ior
apis: [POSIX, MPIIO]
path: /tmp
block_size: [512MiB, 1GiB, 2GiB]
transfer_size: [512KiB, 1MiB, 4MiB, 8MiB]
file_mode: both # fpp, onefile, both
options: ["-u", "-i", "3"]
```
this closes #228
> IOR parameter redesign

- hpcbench/cli/bensh.py
- tests/test_campaign_fd.py
Allows to write campaign path in a dedicated file descriptor.
Fixes #236
> New `--campaign-path-fd` option for ben-sh

- hpcbench/campaign.py
- hpcbench/cli/benwait.py
- hpcbench/toolbox/collections_ext.py
- tests/test_benwait.py
One may want to ensure that a campaign successfully ran before sending metrics to Elasticsearch. So far there is not way to have this information easily.
Instead of creating another cli utility, this pull-request updates `ben-wait` utility so that:
* its exit status tells whether there have been issues or not
* it writes to console a short summary of how benchmarks performed, available in different formats. `--silent` option discards this output.
For instance:
```
$ ben-wait path/to/campaign
node=node01 tag=tag01 benchmark=minigemm category=minigemm attempt=7263eab0-d24f-4ac7-adde-5f752883d739 succeeded=True
$ ben-wait  --format json path/to/campaign
{
"slurm_jobs": [
19473
], 
"benchmarks": [
{
"node": "node01", 
"category": "minigemm", 
"attempt": "7263eab0-d24f-4ac7-adde-5f752883d739", …
```
> ben-wait writes summary to console and exit 1 if a benchmark failed

- hpcbench/driver/benchmark.py
Length of generated directories in a campaign is too big
This pull-request:
* shrinks path length to 8
* use meaningful name for attempts: use *attempt-i* instead of a hash
For instance:
before: `node01/*/test/cpu/d508b691-5a63-4ecc-ad5a-c13a9f763a40/ae138025-0240-4dc0-a374-1f7f51e7fa28/hpcbench.yaml`
after: `node01/*/test/cpu/ceb52ed1/attempt-1/hpcbench.yaml`
> Reduce size of generated directory names

- docs/campaign.rst
- hpcbench/driver/benchmark.py
- hpcbench/driver/executor.py
- hpcbench/toolbox/spack.py
- tests/__init__.py
- tests/test_benwait.py
- tests/test_csv.py
- tests/test_cwd.py
- tests/test_merge.py
- tests/test_slurm.py
- tests/test_spack.py
- tests/test_spack.yaml
- tests/test_srun.py
This pull-request adds capability to specify Spack specs in YAML that are installed before executing benchmarks.
> Manage Spack specifications

- hpcbench/benchmark/babelstream.py
- hpcbench/benchmark/imb.py
- hpcbench/benchmark/nvidia.py
- hpcbench/campaign.py
- hpcbench/cli/bensh.py
- hpcbench/driver/campaign.py
- hpcbench/driver/slurm.py
- hpcbench/templates/hpcbench.yaml.jinja
- hpcbench/toolbox/slurm/cluster.py
- hpcbench/toolbox/spack.py
- tests/__init__.py
- tests/test_environment.py
- tests/test_slurm.py
This patch adds a new way to find absolute path to ` ben-sh` executable used in generated sbatches.
> sbatch: look for ben-sh script in stack

- hpcbench/driver/base.py
- hpcbench/driver/benchmark.py
- tests/__init__.py
- tests/test_environment.py
- tests/test_environment.yaml
Only int, float, and string are accepted.
fixes #256
> benchmark environment variable: enforce type of passed values

- hpcbench/export/es.py
- hpcbench/toolbox/collections_ext.py
- setup.py
- Added a defrost function reversing the freeze operation for dicts and lists
- defrost the connection configuration dict before passing it to Elasticsearch
- Fix Elasticsearch package version to be between 6.0 and 7.0
This allows us to correctly handle Elasticsearch connection parameters needed for HTTP basic auth.
> Enable Elasticsearch HTTP basic auth
